"""empty message

Revision ID: a169221a2b4b
Revises: 4cc0624a5c6f
Create Date: 2024-05-21 20:33:46.776353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a169221a2b4b'
down_revision = '4cc0624a5c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joint_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dip_joint_left_2', sa.Integer(), nullable=True),
    sa.Column('dip_joint_left_3', sa.Integer(), nullable=True),
    sa.Column('dip_joint_left_4', sa.Integer(), nullable=True),
    sa.Column('dip_joint_left_5', sa.Integer(), nullable=True),
    sa.Column('dip_joint_right_2', sa.Integer(), nullable=True),
    sa.Column('dip_joint_right_3', sa.Integer(), nullable=True),
    sa.Column('dip_joint_right_4', sa.Integer(), nullable=True),
    sa.Column('dip_joint_right_5', sa.Integer(), nullable=True),
    sa.Column('thumb_ip_joint_left', sa.Integer(), nullable=True),
    sa.Column('thumb_ip_joint_right', sa.Integer(), nullable=True),
    sa.Column('pip_joint_left_2', sa.Integer(), nullable=True),
    sa.Column('pip_joint_left_3', sa.Integer(), nullable=True),
    sa.Column('pip_joint_left_4', sa.Integer(), nullable=True),
    sa.Column('pip_joint_left_5', sa.Integer(), nullable=True),
    sa.Column('pip_joint_right_2', sa.Integer(), nullable=True),
    sa.Column('pip_joint_right_3', sa.Integer(), nullable=True),
    sa.Column('pip_joint_right_4', sa.Integer(), nullable=True),
    sa.Column('pip_joint_right_5', sa.Integer(), nullable=True),
    sa.Column('mp_joint_left_1', sa.Integer(), nullable=True),
    sa.Column('mp_joint_left_2', sa.Integer(), nullable=True),
    sa.Column('mp_joint_left_3', sa.Integer(), nullable=True),
    sa.Column('mp_joint_left_4', sa.Integer(), nullable=True),
    sa.Column('mp_joint_left_5', sa.Integer(), nullable=True),
    sa.Column('mp_joint_right_1', sa.Integer(), nullable=True),
    sa.Column('mp_joint_right_2', sa.Integer(), nullable=True),
    sa.Column('mp_joint_right_3', sa.Integer(), nullable=True),
    sa.Column('mp_joint_right_4', sa.Integer(), nullable=True),
    sa.Column('mp_joint_right_5', sa.Integer(), nullable=True),
    sa.Column('wrist_joint_hand_left', sa.Integer(), nullable=True),
    sa.Column('wrist_joint_hand_right', sa.Integer(), nullable=True),
    sa.Column('elbow_joint_left', sa.Integer(), nullable=True),
    sa.Column('elbow_joint_right', sa.Integer(), nullable=True),
    sa.Column('shoulder_joint_left', sa.Integer(), nullable=True),
    sa.Column('shoulder_joint_right', sa.Integer(), nullable=True),
    sa.Column('hip_joint_left', sa.Integer(), nullable=True),
    sa.Column('hip_joint_right', sa.Integer(), nullable=True),
    sa.Column('knee_joint_left', sa.Integer(), nullable=True),
    sa.Column('knee_joint_right', sa.Integer(), nullable=True),
    sa.Column('ankle_joint_left', sa.Integer(), nullable=True),
    sa.Column('ankle_joint_right', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_left_1', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_left_2', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_left_3', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_left_4', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_left_5', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_right_1', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_right_2', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_right_3', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_right_4', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_right_5', sa.Integer(), nullable=True),
    sa.Column('distal_joints', sa.Integer(), nullable=True),
    sa.Column('proximal_joints', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hand_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('right_hand_path', sa.String(length=255), nullable=False),
    sa.Column('left_hand_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('crp', sa.Float(), nullable=False),
    sa.Column('esr', sa.Integer(), nullable=False),
    sa.Column('rf', sa.Float(), nullable=False),
    sa.Column('acpa', sa.Float(), nullable=False),
    sa.Column('immunology_score', sa.Integer(), nullable=False),
    sa.Column('inflammation_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('birth_month', sa.Integer(), nullable=True),
    sa.Column('birth_day', sa.Integer(), nullable=True),
    sa.Column('onset_year', sa.Integer(), nullable=True),
    sa.Column('onset_month', sa.Integer(), nullable=True),
    sa.Column('onset_day', sa.Integer(), nullable=True),
    sa.Column('morning_stiffness', sa.String(length=50), nullable=True),
    sa.Column('stiffness_duration', sa.Integer(), nullable=True),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symptom')
    op.drop_table('labo')
    op.drop_table('hand_data')
    op.drop_table('user')
    op.drop_table('joint_data')
    # ### end Alembic commands ###
